"""MemorySummary model.

AI-generated summaries of learning sessions for the Long-Term Memory system.
Phase 1: Stores session summaries.
Phase 2: Summary embeddings enable cross-session semantic recall via pgvector.
Phase 3: Used for spaced repetition scheduling.
"""

import uuid
from datetime import UTC, datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import JSON, DateTime, ForeignKey, Integer, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.database import Base


class MemorySummary(Base):
    """AI-generated summary of a learning session or session segment."""

    __tablename__ = "memory_summaries"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(),
        primary_key=True,
        default=uuid.uuid4,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(),
        ForeignKey("learning_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Summary Content ──────────────────────────────────
    summary_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Key concepts, topics, struggles, strengths (JSON arrays)
    key_concepts: Mapped[list | None] = mapped_column(JSON)
    topics: Mapped[list | None] = mapped_column(JSON)
    struggles: Mapped[list | None] = mapped_column(JSON)
    strengths: Mapped[list | None] = mapped_column(JSON)

    # ── Phase 2: pgvector embedding for semantic search ──
    # 768-dimensional embedding of summary_text for cross-session recall
    # Generated by the embedding service when a summary is created
    summary_embedding: Mapped[list[float] | None] = mapped_column(
        Vector(768),
        nullable=True,
    )

    # ── Metadata ─────────────────────────────────────────
    message_count: Mapped[int] = mapped_column(Integer, default=0)
    model_used: Mapped[str | None] = mapped_column(String(100))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
    )

    def __repr__(self) -> str:
        concepts = f"{len(self.key_concepts)} concepts" if self.key_concepts else "no concepts"
        return f"<MemorySummary {self.id}: {concepts}>"
