"""
Quiz model for AI-generated assessments.

Each quiz is generated by the AI based on a topic/subject and
contains a list of questions stored as JSON. Users can answer
questions and receive a score with explanations.

Questions are stored as a JSON array with this structure:
[
    {
        "id": "uuid",
        "question": "What is...?",
        "type": "multiple_choice | true_false | short_answer",
        "options": ["A", "B", "C", "D"],  # null for short_answer
        "correct_answer": "B",
        "explanation": "Because..."
    }
]
"""

import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import String, Integer, DateTime, Text, ForeignKey, JSON, Uuid, Float
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.database import Base


class Quiz(Base):
    __tablename__ = "quizzes"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(),
        primary_key=True,
        default=uuid.uuid4,
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(),
        ForeignKey("learning_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Quiz metadata
    topic: Mapped[str] = mapped_column(String(200), nullable=False)
    difficulty: Mapped[str] = mapped_column(
        String(20),
        default="balanced",
    )
    question_count: Mapped[int] = mapped_column(Integer, default=0)

    # Questions stored as JSON array
    questions: Mapped[list[dict[str, Any]]] = mapped_column(JSON, default=list)

    # Status: generated, in_progress, completed
    status: Mapped[str] = mapped_column(String(20), default="generated")

    # Scoring
    score: Mapped[int | None] = mapped_column(Integer)
    total_points: Mapped[int | None] = mapped_column(Integer)

    # Model used to generate
    model_used: Mapped[str | None] = mapped_column(String(100))

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    def __repr__(self) -> str:
        return f"<Quiz {self.topic} ({self.status})>"

    @property
    def correct_count(self) -> int:
        """Count of correctly answered questions."""
        if not self.questions:
            return 0
        return sum(
            1 for q in self.questions
            if q.get("user_answer") is not None and q.get("user_answer") == q.get("correct_answer")
        )

    @property
    def answered_count(self) -> int:
        """Count of answered questions."""
        if not self.questions:
            return 0
        return sum(1 for q in self.questions if q.get("user_answer") is not None)

    @property
    def is_complete(self) -> bool:
        """All questions have been answered."""
        return self.answered_count >= self.question_count and self.question_count > 0
