"""
Study Plan model for AI-generated personalized learning paths.

Each study plan is generated by the AI based on user goals, subjects,
and experience level. It contains milestones stored as JSON with
weekly learning objectives, topics, estimated time, and resources.
"""

import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import String, Integer, DateTime, Text, ForeignKey, JSON, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.database import Base


class StudyPlan(Base):
    __tablename__ = "study_plans"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(),
        primary_key=True,
        default=uuid.uuid4,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Plan metadata
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    goal: Mapped[str] = mapped_column(String(50))  # exam_prep, curiosity, skill_building, research
    subjects: Mapped[list[str]] = mapped_column(JSON, default=list)
    experience_level: Mapped[str] = mapped_column(String(20), default="beginner")

    # Estimated duration
    estimated_duration_weeks: Mapped[int] = mapped_column(Integer, default=4)

    # Milestones stored as JSON array
    milestones: Mapped[list[dict[str, Any]]] = mapped_column(JSON, default=list)

    # Status: active, completed, archived
    status: Mapped[str] = mapped_column(String(20), default="active")

    # Model used to generate
    model_used: Mapped[str | None] = mapped_column(String(100))

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    def __repr__(self) -> str:
        return f"<StudyPlan {self.title} ({self.status})>"
